// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ZddBgnXEYmXnxMNKlsp56USy5DY09_4',
    appId: '1:542579527140:web:5615210a10ca0b4d280bf1',
    messagingSenderId: '542579527140',
    projectId: 'musicfinder-5db79',
    authDomain: 'musicfinder-5db79.firebaseapp.com',
    storageBucket: 'musicfinder-5db79.appspot.com',
    measurementId: 'G-ZYP22J4XRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYvwMEAbUz_SsEBfyjIou00dlajP8MPCg',
    appId: '1:542579527140:android:ae2d3a87608c56b4280bf1',
    messagingSenderId: '542579527140',
    projectId: 'musicfinder-5db79',
    storageBucket: 'musicfinder-5db79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYlRIWm0Rcrp4B_sOchDnLiyCOvY6h6dY',
    appId: '1:542579527140:ios:5e2fa4ef503a8e2c280bf1',
    messagingSenderId: '542579527140',
    projectId: 'musicfinder-5db79',
    storageBucket: 'musicfinder-5db79.appspot.com',
    iosClientId: '542579527140-dsi44kl5rsp5g6lm2d34itvebb965m5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.practica1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYlRIWm0Rcrp4B_sOchDnLiyCOvY6h6dY',
    appId: '1:542579527140:ios:5e2fa4ef503a8e2c280bf1',
    messagingSenderId: '542579527140',
    projectId: 'musicfinder-5db79',
    storageBucket: 'musicfinder-5db79.appspot.com',
    iosClientId: '542579527140-dsi44kl5rsp5g6lm2d34itvebb965m5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.practica1',
  );
}
